project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 0"
          href: Hands_On_Exercise/Hands_On_Exercise_0/Hands_On_Exercise_0.html
        - text: "Hands-on Exercise 1"
          href: Hands_On_Exercise/Hands_On_Exercise_1/Hands_On_Exercise_1.html
        - text: "Hands-on Exercise 2"
          href: Hands_On_Exercise/Hands_On_Exercise_2/Hands_On_Exercise_2.html
        - text: "Hands-on Exercise 3"
          href: Hands_On_Exercise/Hands_On_Exercise_3/Hands_On_Exercise_3.html
        - text: "Hands-on Exercise 4"
          href: Hands_On_Exercise/Hands_On_Exercise_4/Hands_On_Exercise_4.html
        - text: "Hands-on Exercise 5"
          href: Hands_On_Exercise/Hands_On_Exercise_5/Hands_On_Exercise_5.html
          
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 4"
          href: In_Class_Exercise/In_Class_Exercise_4/In_Class_Exercise_4.html
          
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-Home Exercise 1"

      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

