project:
  type: website

website:
  title: "ISSS608 Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 0"
          href: Hands_On_Exercise/Hands_On_Exercise_0/Hands_On_Exercise_0.html
        - text: "Hands-on Exercise 1"
          href: Hands_On_Exercise/Hands_On_Exercise_1/Hands_On_Exercise_1.html
          
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 0"
          
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-Home Exercise 0"

      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

