---
title: "In_Class_Exercise_5"
format: html
date: "February 15 2025"
date-modified: "last-modified"
execute:
  freeze: true
  echo: true
  eval: true
  warning: false
---

# Getting Started

```{r}
pacman::p_load(tidyverse,readxl,SmartEDA, easystats, gtsummary, ggstatsplot)
```

# Importing Data

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls")
```

# Understanding the Data

## Data Overview

```{R}
summary(car_resale)
```

```{r}
car_resale %>%
  ExpData(type =1)
```

```{R}
car_resale %>%
  ExpData(type =2)
```

```{R}
list(car_resale)
```

```{R}
cols <- c("Mfg_Month","HP_Bin","CC_bin","Doors","Gears","Cylinders","Fuel_Type","Color","Met_Color","Automatic","Mfr_Guarantee","BOVAG_Guarantee","ABS","Airbag_1","Airbag_2","Airco","Automatic_airco","Boardcomputer","CD_Player","Central_Lock","Powered_Windows","Power_Steering","Radio","Mistlamps","Sport_Model","Backseat_Divider","Metallic_Rim","Radio_cassette","Tow_Bar")

car_resale <- read_xls("data/ToyotaCorolla.xls",
                       sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate_each_(funs(factor(.)),cols)
```

```{R}
car_resale %>%
  ExpData(type =1)
```

```{r}
car_resale %>%
  ExpData(type =2)
```

```{R}
car_resale %>%
  ExpNumViz(target = NULL,
            nlim=10,
            Page=c(2,2)
            )
```

```{R}
car_resale %>% 
  ExpNumViz(target = "Price", nlim=10, Page=c(2,2)) 
```

```{R}
#| fig-width: 12
#| fig-height: 10
car_resale %>%
  ExpCatViz(target=NULL,
            col="sky blue",
            clim=10,
            margin=2,
            Page=c(4,4),
            sample=16)
```

```{R}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period,data=
              car_resale)
model
```

```{R}
check_collinearity(model)
```

```{R}
check_c = check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period, data=
               car_resale)
check_normality(model1)
```

```{R}
check_heteroscedasticity(model1)
```

```{R}
tbl_regression(model1,
               intercept = TRUE) %>%
  add_glance_source_note(
    label = list(sigma ~ "\U03C3"),
    include = c(r.squared, adj.r.squared,
                AIC, statistic,
                p.value, sigma)
  )
```

```{R}
p_model1 <- parameters(model1)
```

```{R}
plot(p_model1)
```

```{R}
ggcoefstats(model1,
            output= "plot")
```
